#端口配置
server:
  port: 80
#环境配置
spring:
  profiles:
    active: test
#mybatis扫描包配置
mybatis-plus:
  typeAliasesPackage: com.gblfy.editor.entity
  mapper-locations: classpath:com/gblfy/editor/**/mapping/*.xml

